from __future__ import annotations

from pathlib import Path
import subprocess
from typing import Any

from ._axioms import (
    AXIOM_NAMESPACE_NAMES,
    AffineNode,
    AutodiffNode,
    AxiomNode,
    AxiomStage,
    BoundAxiomNode,
    BoundNamespaces,
    ClosNode,
    CompileNode,
    CoreNode,
    DemoNode,
    DirectNode,
    GpuNode,
    MathNode,
    MatrixNode,
    MemNode,
    OrdNode,
    ReflyNode,
    RegexNode,
    TensorNode,
    TupleNode,
    VecNode,
)
class Def:
    def type(self) -> Def: ...
    def var(self) -> Def: ...
    def proj(self, *args: int) -> Def: ...
    def externalize(self) -> None: ...
    def dump(self) -> None: ...
    def to_string(self) -> str: ...
    def value(self) -> int: ...
    def set(self, arg0: str) -> Def: ...
    def num_projs(self) -> int: ...
    def projs(self, arg0: int) -> list[Def]: ...


class Lit(Def):
    def value(self) -> int: ...


class Pi(Def): ...


class Lam(Def):
    def var(self) -> Def: ...
    def app(self, arg0: bool, arg1: Def, arg2: list[Def]) -> Lam: ...


class Level:
    Error: Level
    Warn: Level
    Info: Level
    Verbose: Level
    Debug: Level


class Log:
    def set_stdout(self) -> Log: ...
    def set(self, arg0: Level) -> Log: ...


class AST:
    def __init__(self, arg0: World) -> None: ...


class Parser:
    def __init__(self, arg0: AST) -> None: ...
    def plugin(self, arg0: str) -> None: ...


class PyParser:
    def __init__(self, arg0: Parser) -> None: ...
    def plugin(self, arg0: str) -> None: ...


class World:
    def write(self) -> None: ...
    def annex(self, arg0: Any) -> Def: ...
    def annex_name(self, name: str) -> Def: ...
    def top_nat(self) -> Def: ...
    def type_bool(self) -> Def: ...
    def type_i8(self) -> Def: ...
    def type_i32(self) -> Def: ...
    def lit_nat_0(self) -> Lit: ...
    def lit_nat(self, arg0: int) -> Lit: ...
    def lit(self, arg0: Def, arg1: int) -> Lit: ...
    def lit_i8(self, arg0: int) -> Lit: ...
    def lit_i32(self, arg0: int) -> Lit: ...
    def type_idx(self, arg0: Def | int) -> Def: ...
    def lit_idx(self, arg0: int, arg1: int) -> Lit: ...
    def cn(self, arg0: list[Def]) -> Def: ...
    def implicit_app(self, arg0: Def, arg1: list[Def]) -> Def: ...
    def app(self, arg0: Def, arg1: list[Def]) -> Def: ...
    def call(self, callee: str | Def, *stages: object, implicit: bool = False) -> Def: ...
    def tuple(self, arg0: list[Def]) -> Def: ...
    def bot(self, arg0: Def) -> Def: ...
    def sym(self, arg0: str) -> Any: ...
    def mut_fun2(self, arg0: list[Def], arg1: list[Def]) -> Lam: ...
    def mut_fun(self, arg0: Def, arg1: list[Def]) -> Lam: ...
    def arr(self, arg0: Def, arg1: Def) -> Def: ...
    def optimize(self) -> None: ...
    def dot(self, arg0: str, arg1: bool, arg2: bool) -> None: ...
    def mut_con(self, arg0: list[Def]) -> Lam: ...
    def annex_by_id(self, arg0: int) -> Def: ...


class Driver:
    def __init__(self) -> None: ...
    def world(self) -> World: ...
    def add_import(self, path: str, name: str) -> Path: ...
    def add_search_path(self, path: Path) -> None: ...
    def log(self) -> Log: ...
    def backend(self, backend: str, output_file_name: str, world: World) -> None: ...
    def load_plugins(self, plugins: list[str]) -> None: ...
    def load_pluins(self, plugins: list[str]) -> None: ...


Affine: AffineNode
Autodiff: AutodiffNode
Clos: ClosNode
Compile: CompileNode
Core: CoreNode
Demo: DemoNode
Direct: DirectNode
Gpu: GpuNode
Math: MathNode
Matrix: MatrixNode
Mem: MemNode
Opt: AxiomNode
Ord: OrdNode
Refly: ReflyNode
Regex: RegexNode
Tensor: TensorNode
Tuple: TupleNode
Vec: VecNode


def plugin_search_paths() -> list[Path]: ...
def configure_driver(driver: Driver) -> Driver: ...
def make_driver(*plugins: str, log_level: Level | None = None, set_stdout: bool = False) -> Driver: ...
def bind(world: World) -> BoundNamespaces: ...
def list_axioms() -> dict[str, tuple[str, ...]]: ...
def build_native_main_i32(world: World, result: Def, name: str = "main") -> Lam: ...
def emit_llvm(driver: Driver, world: World, output_path: str | Path) -> Path: ...
def clang_compile(
    llvm_ir: str | Path,
    output_path: str | Path,
    *,
    clang: str = "clang",
    extra_args: list[str] = ...,
) -> Path: ...
def build_native_executable(
    driver: Driver,
    world: World,
    stem: str | Path,
    *,
    clang: str = "clang",
    extra_args: list[str] = ...,
) -> Path: ...
def run_native_executable(
    executable: str | Path,
    args: list[str] = ...,
    *,
    check: bool = False,
) -> subprocess.CompletedProcess[str]: ...
def matrix_i32(world: World, rows: list[list[int]]) -> Def: ...
def matrix_to_list(matrix: Def) -> list[list[int]]: ...
def transpose_2d(world: World, matrix: Def) -> Def: ...
def matmul_i32(world: World, lhs: Def, rhs: Def) -> Def: ...
