from __future__ import annotations

from pathlib import Path
import pprint
import re
import subprocess


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "python" / "mim" / "_axioms_generated.py"
STUB_OUTPUT = ROOT / "python" / "mim" / "_axioms.pyi"


def find_plugin_dir() -> Path:
    venv_candidates = sorted(ROOT.glob(".venv/lib/python*/site-packages/mim/plugins"))
    candidates = [
        ROOT / "python" / "mim" / "plugins",
        *venv_candidates,
        ROOT / "build" / "cp313-cp313-linux_x86_64" / "mim" / "plugins",
        ROOT / "build-nopy" / "lib" / "mim",
        ROOT / "build-pr300" / "lib" / "mim",
        ROOT / "build" / "cp313-cp313-linux_x86_64" / "lib" / "mim",
        ROOT / "build" / "lib" / "mim",
    ]

    for path in candidates:
        if path.exists():
            return path

    raise FileNotFoundError("could not locate MimIR plugin directory")


def iter_declarations(path: Path) -> list[str]:
    declarations: list[str] = []
    current: list[str] = []
    for raw_line in path.read_text().splitlines():
        line = raw_line.split("//", 1)[0].strip()
        if not line:
            continue
        current.append(line)
        if line.endswith(";"):
            declarations.append(" ".join(current))
            current = []
    return declarations


def parse_symbols(path: Path) -> list[str]:
    symbols: list[str] = []

    for declaration in iter_declarations(path):
        if declaration.startswith("axm %"):
            match = re.match(r"^axm\s+(%[A-Za-z0-9_.]+)(?:\(([^)]*)\))?", declaration)
            if match is None:
                continue
            base, subdecls = match.groups()
            if subdecls is None:
                symbols.append(base)
                continue

            for item in subdecls.split(","):
                for name in (part.strip() for part in item.split("=")):
                    if name:
                        symbols.append(f"{base}.{name}")
            continue

        match = re.match(r"^(?:lam|let)\s+(%[A-Za-z0-9_.]+)", declaration)
        if match is not None:
            symbols.append(match.group(1))

    return sorted(set(symbols))


def public_plugin_name(plugin: str) -> str:
    return "".join(part.capitalize() for part in plugin.split("_"))


def insert(tree: dict[str, object], parts: list[str], symbol: str) -> None:
    cursor = tree
    for part in parts[:-1]:
        child = cursor.get(part)
        if not isinstance(child, dict):
            child = {}
            cursor[part] = child
        cursor = child
    cursor[parts[-1]] = symbol


def build_data() -> tuple[dict[str, dict[str, object]], tuple[str, ...]]:
    plugin_dir = find_plugin_dir()
    axiom_trees: dict[str, dict[str, object]] = {}

    for path in sorted(plugin_dir.glob("*.mim")):
        plugin = path.stem
        symbols = parse_symbols(path)

        tree: dict[str, object] = {}
        for symbol in symbols:
            rest = symbol[1:].split(".")[1:]
            if rest:
                insert(tree, rest, symbol)
        axiom_trees[plugin] = tree

    namespace_names = tuple(public_plugin_name(plugin) for plugin in sorted(axiom_trees))
    return axiom_trees, namespace_names


def main() -> None:
    axiom_trees, namespace_names = build_data()

    class _RawPrettyPrinter(pprint.PrettyPrinter):
        def format(self, obj: object, context: dict[int, object], maxlevels: int, level: int) -> tuple[str, bool, bool]:
            if isinstance(obj, str) and obj.startswith("%"):
                return (f"r{obj!r}", True, False)
            return super().format(obj, context, maxlevels, level)

    printer = _RawPrettyPrinter(width=100, sort_dicts=True)

    lines = [
        "from __future__ import annotations",
        "",
        "# This file is generated by scripts/generate_axiom_wrappers.py.",
        "# Do not edit manually.",
        "",
        f"AXIOM_TREES = {printer.pformat(axiom_trees)}",
        "",
        f"AXIOM_NAMESPACE_NAMES = {printer.pformat(namespace_names)}",
        "",
        "__all__ = ['AXIOM_TREES', 'AXIOM_NAMESPACE_NAMES']",
        "",
    ]
    OUTPUT.write_text("\n".join(lines))

    # Returns only dict-valued children (grouping nodes).
    def dict_children(tree: dict[str, object]) -> list[tuple[str, dict[str, object]]]:
        return [(name, child) for name, child in sorted(tree.items()) if isinstance(child, dict)]

    # Returns all children: strings (leaves) and dicts (grouping nodes).
    def all_children(tree: dict[str, object]) -> list[tuple[str, object]]:
        return [(name, child) for name, child in sorted(tree.items()) if isinstance(child, (str, dict))]

    def class_name(parts: list[str]) -> str:
        def sanitize(part: str) -> str:
            pieces = [piece for piece in re.split(r"[^A-Za-z0-9]+", part) if piece]
            text = "".join(piece[:1].upper() + piece[1:] for piece in pieces) or "Node"
            if text[:1].isdigit():
                text = f"N{text}"
            return text

        return "".join(sanitize(part) for part in parts) + "Node"

    visited: set[str] = set()  # recursion guard
    emitted: set[str] = set()  # classes actually written
    stub_lines = [
        "from __future__ import annotations",
        "",
        "# This file is generated by scripts/generate_axiom_wrappers.py.",
        "# Do not edit manually.",
        "",
        "from typing import Sequence, TypeAlias",
        "",
        "from ._mim_core import Def, World",
        "",
        "AxiomStage: TypeAlias = Def | Sequence[Def]",
        "",
        "",
        "class AxiomNode:",
        "    @property",
        "    def symbol(self) -> str | None: ...",
        "    def __call__(self, world: World, *stages: AxiomStage, implicit: bool = False) -> Def: ...",
        "    def __getattr__(self, name: str) -> AxiomNode: ...",
        "",
    ]

    def emit_node(parts: list[str], tree: dict[str, object]) -> None:
        name = class_name(parts)
        if name in visited:
            return
        visited.add(name)

        # Recurse into grouping children before emitting this class (children-first order).
        for child_name, child_tree in dict_children(tree):
            emit_node(parts + [child_name], child_tree)

        children = all_children(tree)
        if not children:
            return

        emitted.add(name)
        stub_lines.append(f"class {name}(AxiomNode):")
        for child_name, child_val in children:
            # Use a specific typed class only when the child is a grouping node with its own children.
            if isinstance(child_val, dict) and all_children(child_val):
                child_type = class_name(parts + [child_name])
            else:
                child_type = "AxiomNode"
            stub_lines.append(f"    {child_name}: {child_type}")
        stub_lines.append("")

    for plugin, tree in sorted(axiom_trees.items()):
        emit_node([public_plugin_name(plugin)], tree)

    stub_lines.extend(
        [
            "AXIOM_NAMESPACE_NAMES: tuple[str, ...]",
            "",
            "",
            "def list_axioms() -> dict[str, tuple[str, ...]]: ...",
            "",
            "",
        ]
    )

    for plugin in sorted(axiom_trees):
        public = public_plugin_name(plugin)
        name = class_name([public])
        stub_lines.append(f"{public}: {name if name in emitted else 'AxiomNode'}")

    stub_lines.append("")
    STUB_OUTPUT.write_text("\n".join(stub_lines))

    subprocess.run(["ruff", "format", str(OUTPUT), str(STUB_OUTPUT)], check=True)


if __name__ == "__main__":
    main()
