from __future__ import annotations

from pathlib import Path

from ._mim_core import AST, Def, Driver, Lam, Level, Lit, Log, Parser, Pi, PyParser, World

__all__: list[str]


def plugin_search_paths() -> list[Path]: ...
def configure_driver(driver: Driver) -> Driver: ...
def matrix_i32(world: World, rows: list[list[int]]) -> Def: ...
def matrix_to_list(matrix: Def) -> list[list[int]]: ...
def transpose_2d(world: World, matrix: Def) -> Def: ...
def matmul_i32(world: World, lhs: Def, rhs: Def) -> Def: ...
