from __future__ import annotations

# This file is generated by scripts/generate_axiom_wrappers.py.
# Do not edit manually.

from typing import Sequence, TypeAlias

from ._mim_core import Def, World

AxiomStage: TypeAlias = Def | Sequence[Def]

class AxiomNode:
    @property
    def symbol(self) -> str | None: ...
    def __call__(
        self, world: World, *stages: AxiomStage, implicit: bool = False
    ) -> Def: ...
    def __getattr__(self, name: str) -> AxiomNode: ...

class AffineNode(AxiomNode):
    For: AxiomNode
    lower_for_phase: AxiomNode

class AutodiffNode(AxiomNode):
    AD: AxiomNode
    Tangent: AxiomNode
    ad: AxiomNode
    add: AxiomNode
    eval_pass: AxiomNode
    sum: AxiomNode
    zero: AxiomNode
    zero_repl: AxiomNode

class ClosAttrNode(AxiomNode):
    bottom: AxiomNode
    esc: AxiomNode
    freeBB: AxiomNode
    fstclassBB: AxiomNode
    returning: AxiomNode

class ClosNode(AxiomNode):
    BufPtr: AxiomNode
    alloc_jmpbuf: AxiomNode
    attr: ClosAttrNode
    branch_clos_pass: AxiomNode
    clos2sjlj_pass: AxiomNode
    clos_conv_phase: AxiomNode
    clos_conv_prep_pass: AxiomNode
    longjmp: AxiomNode
    lower_typed_clos_phase: AxiomNode
    lower_typed_clos_prep_pass: AxiomNode
    setjmp: AxiomNode

class CompileNode(AxiomNode):
    Pass: AxiomNode
    Phase: AxiomNode
    Repl: AxiomNode
    beta_red_pass: AxiomNode
    beta_red_phase: AxiomNode
    branch_normalize_phase: AxiomNode
    cleanup_phase: AxiomNode
    eta_exp_pass: AxiomNode
    eta_exp_phase: AxiomNode
    eta_red_pass: AxiomNode
    eta_red_phase: AxiomNode
    internal_cleanup_phase: AxiomNode
    is_loaded: AxiomNode
    lam_spec_pass: AxiomNode
    null_pass: AxiomNode
    null_phase: AxiomNode
    null_repl: AxiomNode
    pass2phase: AxiomNode
    passes: AxiomNode
    phases: AxiomNode
    prefix_cleanup_phase: AxiomNode
    repl2phase: AxiomNode
    repls: AxiomNode
    ret_wrap_phase: AxiomNode
    scalarize_pass: AxiomNode
    sym_expr_opt: AxiomNode
    tail_rec_elim_pass: AxiomNode

class CoreBit1Node(AxiomNode):
    f: AxiomNode
    id: AxiomNode
    neg: AxiomNode
    t: AxiomNode

class CoreBit2Node(AxiomNode):
    and_: AxiomNode
    ciff: AxiomNode
    f: AxiomNode
    fst: AxiomNode
    iff: AxiomNode
    nand: AxiomNode
    nciff: AxiomNode
    nfst: AxiomNode
    niff: AxiomNode
    nor: AxiomNode
    nsnd: AxiomNode
    nxor: AxiomNode
    or_: AxiomNode
    snd: AxiomNode
    t: AxiomNode
    xor_: AxiomNode

class CoreConvNode(AxiomNode):
    s: AxiomNode
    u: AxiomNode

class CoreDivNode(AxiomNode):
    sdiv: AxiomNode
    srem: AxiomNode
    udiv: AxiomNode
    urem: AxiomNode

class CoreExtremaNode(AxiomNode):
    SM: AxiomNode
    Sm: AxiomNode
    sM: AxiomNode
    sm: AxiomNode
    smax: AxiomNode
    smin: AxiomNode
    umax: AxiomNode
    umin: AxiomNode

class CoreIcmpNode(AxiomNode):
    XYGLE: AxiomNode
    XYGLe: AxiomNode
    XYGlE: AxiomNode
    XYGle: AxiomNode
    XYgLE: AxiomNode
    XYgLe: AxiomNode
    XYglE: AxiomNode
    XYgle: AxiomNode
    XyGLE: AxiomNode
    XyGLe: AxiomNode
    XyGlE: AxiomNode
    XyGle: AxiomNode
    XygLE: AxiomNode
    XygLe: AxiomNode
    XyglE: AxiomNode
    Xygle: AxiomNode
    e: AxiomNode
    f: AxiomNode
    ne: AxiomNode
    sg: AxiomNode
    sge: AxiomNode
    sl: AxiomNode
    sle: AxiomNode
    t: AxiomNode
    ug: AxiomNode
    uge: AxiomNode
    ul: AxiomNode
    ule: AxiomNode
    xYGLE: AxiomNode
    xYGLe: AxiomNode
    xYGlE: AxiomNode
    xYGle: AxiomNode
    xYgLE: AxiomNode
    xYgLe: AxiomNode
    xYglE: AxiomNode
    xYgle: AxiomNode
    xyGLE: AxiomNode
    xyGLe: AxiomNode
    xyGlE: AxiomNode
    xyGle: AxiomNode
    xygLE: AxiomNode
    xygLe: AxiomNode
    xyglE: AxiomNode
    xygle: AxiomNode

class CoreModeNode(AxiomNode):
    US: AxiomNode
    Us: AxiomNode
    nsw: AxiomNode
    nusw: AxiomNode
    nuw: AxiomNode
    uS: AxiomNode
    us: AxiomNode

class CoreNatNode(AxiomNode):
    add: AxiomNode
    mul: AxiomNode
    sub: AxiomNode

class CoreNcmpNode(AxiomNode):
    GLE: AxiomNode
    GLe: AxiomNode
    GlE: AxiomNode
    Gle: AxiomNode
    e: AxiomNode
    f: AxiomNode
    g: AxiomNode
    gLE: AxiomNode
    gLe: AxiomNode
    ge: AxiomNode
    glE: AxiomNode
    gle: AxiomNode
    l: AxiomNode
    le: AxiomNode
    ne: AxiomNode
    t: AxiomNode

class CorePeNode(AxiomNode):
    hlt: AxiomNode
    is_closed: AxiomNode
    run: AxiomNode

class CoreShrNode(AxiomNode):
    a: AxiomNode
    l: AxiomNode

class CoreTraitNode(AxiomNode):
    align: AxiomNode
    size: AxiomNode

class CoreWrapNode(AxiomNode):
    add: AxiomNode
    mul: AxiomNode
    shl: AxiomNode
    sub: AxiomNode

class CoreNode(AxiomNode):
    abs: AxiomNode
    bit1: CoreBit1Node
    bit2: CoreBit2Node
    bitcast: AxiomNode
    conv: CoreConvNode
    div: CoreDivNode
    extrema: CoreExtremaNode
    icmp: CoreIcmpNode
    idx: AxiomNode
    idx_unsafe: AxiomNode
    minus: AxiomNode
    mode: CoreModeNode
    nat: CoreNatNode
    ncmp: CoreNcmpNode
    pe: CorePeNode
    select: AxiomNode
    shr: CoreShrNode
    trait: CoreTraitNode
    wrap: CoreWrapNode

class DemoNode(AxiomNode):
    const_idx: AxiomNode

class DirectNode(AxiomNode):
    cps2ds: AxiomNode
    cps2ds_dep: AxiomNode
    cps2ds_phase: AxiomNode
    ds2cps_phase: AxiomNode

class GpuNode(AxiomNode):
    ConstM: AxiomNode
    ConstPtr: AxiomNode
    DefaultStream: AxiomNode
    GlobalM: AxiomNode
    GlobalPtr: AxiomNode
    LocalM: AxiomNode
    LocalPtr: AxiomNode
    SharedM: AxiomNode
    SharedPtr: AxiomNode
    Stream: AxiomNode
    addr_space_const: AxiomNode
    addr_space_global: AxiomNode
    addr_space_local: AxiomNode
    addr_space_shared: AxiomNode
    alloc: AxiomNode
    alloc_async: AxiomNode
    alloc_copy: AxiomNode
    alloc_copy_async: AxiomNode
    copy_to_device: AxiomNode
    copy_to_device_async: AxiomNode
    copy_to_host: AxiomNode
    copy_to_host_async: AxiomNode
    free: AxiomNode
    free_async: AxiomNode
    launch: AxiomNode
    launch_with_smem: AxiomNode
    malloc2gpualloc_repl: AxiomNode
    stream_deinit: AxiomNode
    stream_init: AxiomNode
    stream_sync: AxiomNode
    sync_work_items: AxiomNode
    synced_scope: AxiomNode

class MathArithNode(AxiomNode):
    add: AxiomNode
    div: AxiomNode
    mul: AxiomNode
    rem: AxiomNode
    sub: AxiomNode

class MathCmpNode(AxiomNode):
    UGLE: AxiomNode
    UGLe: AxiomNode
    UGlE: AxiomNode
    UGle: AxiomNode
    UgLE: AxiomNode
    UgLe: AxiomNode
    UglE: AxiomNode
    Ugle: AxiomNode
    e: AxiomNode
    f: AxiomNode
    g: AxiomNode
    ge: AxiomNode
    l: AxiomNode
    le: AxiomNode
    ne: AxiomNode
    o: AxiomNode
    t: AxiomNode
    u: AxiomNode
    uGLE: AxiomNode
    uGLe: AxiomNode
    uGlE: AxiomNode
    uGle: AxiomNode
    ue: AxiomNode
    ug: AxiomNode
    ugLE: AxiomNode
    ugLe: AxiomNode
    uge: AxiomNode
    uglE: AxiomNode
    ugle: AxiomNode
    ul: AxiomNode
    ule: AxiomNode
    une: AxiomNode

class MathConvNode(AxiomNode):
    f2f: AxiomNode
    f2s: AxiomNode
    f2u: AxiomNode
    s2f: AxiomNode
    u2f: AxiomNode

class MathErNode(AxiomNode):
    f: AxiomNode
    fc: AxiomNode

class MathExpNode(AxiomNode):
    LBB: AxiomNode
    LBb: AxiomNode
    LbB: AxiomNode
    Lbb: AxiomNode
    bin: AxiomNode
    dec: AxiomNode
    exp: AxiomNode
    exp10: AxiomNode
    exp2: AxiomNode
    lBB: AxiomNode
    lBb: AxiomNode
    lbB: AxiomNode
    lbb: AxiomNode
    log: AxiomNode
    log10: AxiomNode
    log2: AxiomNode

class MathExtremaNode(AxiomNode):
    IM: AxiomNode
    Im: AxiomNode
    fmax: AxiomNode
    fmin: AxiomNode
    iM: AxiomNode
    ieee754max: AxiomNode
    ieee754min: AxiomNode
    im: AxiomNode

class MathGammaNode(AxiomNode):
    l: AxiomNode
    t: AxiomNode

class MathRoundNode(AxiomNode):
    c: AxiomNode
    f: AxiomNode
    r: AxiomNode
    t: AxiomNode

class MathRtNode(AxiomNode):
    cb: AxiomNode
    sq: AxiomNode

class MathTriNode(AxiomNode):
    AHFF: AxiomNode
    AHFf: AxiomNode
    AHfF: AxiomNode
    AHff: AxiomNode
    AhFF: AxiomNode
    AhFf: AxiomNode
    AhfF: AxiomNode
    Ahff: AxiomNode
    a: AxiomNode
    aHFF: AxiomNode
    aHFf: AxiomNode
    aHfF: AxiomNode
    aHff: AxiomNode
    acos: AxiomNode
    acosh: AxiomNode
    ahFF: AxiomNode
    ahFf: AxiomNode
    ahfF: AxiomNode
    ahff: AxiomNode
    asin: AxiomNode
    asinh: AxiomNode
    atan: AxiomNode
    atanh: AxiomNode
    cos: AxiomNode
    cosh: AxiomNode
    h: AxiomNode
    sin: AxiomNode
    sinh: AxiomNode
    tan: AxiomNode
    tanh: AxiomNode

class MathNode(AxiomNode):
    AMDFP24: AxiomNode
    BF16: AxiomNode
    F: AxiomNode
    F16: AxiomNode
    F32: AxiomNode
    F64: AxiomNode
    NVTF32: AxiomNode
    PXR24: AxiomNode
    abs: AxiomNode
    amdfp24: AxiomNode
    arith: MathArithNode
    bf16: AxiomNode
    cmp: MathCmpNode
    conv: MathConvNode
    er: MathErNode
    exp: MathExpNode
    extrema: MathExtremaNode
    f16: AxiomNode
    f32: AxiomNode
    f64: AxiomNode
    gamma: MathGammaNode
    minus: AxiomNode
    nvtf32: AxiomNode
    pow: AxiomNode
    pxr24: AxiomNode
    round: MathRoundNode
    rrt: AxiomNode
    rt: MathRtNode
    sgn: AxiomNode
    slf: AxiomNode
    tri: MathTriNode

class MatrixNode(AxiomNode):
    Mat: AxiomNode
    constMat: AxiomNode
    init: AxiomNode
    insert: AxiomNode
    lower_matrix_high_level_map_reduce: AxiomNode
    lower_matrix_low_level: AxiomNode
    lower_matrix_medium_level: AxiomNode
    map_reduce: AxiomNode
    prod: AxiomNode
    read: AxiomNode
    shape: AxiomNode
    sum: AxiomNode
    transpose: AxiomNode

class MemNode(AxiomNode):
    M: AxiomNode
    Ptr: AxiomNode
    Ptr0: AxiomNode
    add_mem_phase: AxiomNode
    alloc: AxiomNode
    alloc2malloc_repl: AxiomNode
    copy_prop_pass: AxiomNode
    free: AxiomNode
    lea: AxiomNode
    load: AxiomNode
    malloc: AxiomNode
    mslot: AxiomNode
    remem: AxiomNode
    remem_repl: AxiomNode
    reshape_arg: AxiomNode
    reshape_flat: AxiomNode
    reshape_mode: AxiomNode
    reshape_pass: AxiomNode
    slot: AxiomNode
    ssa_pass: AxiomNode
    store: AxiomNode

class OrdContainsNode(AxiomNode):
    map: AxiomNode
    set: AxiomNode

class OrdInitNode(AxiomNode):
    map: AxiomNode
    set: AxiomNode

class OrdInsertNode(AxiomNode):
    map: AxiomNode
    set: AxiomNode

class OrdSizeNode(AxiomNode):
    map: AxiomNode
    set: AxiomNode

class OrdNode(AxiomNode):
    Key: AxiomNode
    Map: AxiomNode
    Set: AxiomNode
    contains: OrdContainsNode
    create_map: AxiomNode
    create_set: AxiomNode
    get: AxiomNode
    init: OrdInitNode
    insert: OrdInsertNode
    is_empty_map: AxiomNode
    is_empty_set: AxiomNode
    size: OrdSizeNode

class ReflyDbgNode(AxiomNode):
    perm: AxiomNode
    tmp: AxiomNode

class ReflyEquivNode(AxiomNode):
    AE: AxiomNode
    Ae: AxiomNode
    aE: AxiomNode
    ae: AxiomNode
    alpha_eq: AxiomNode
    alpha_ne: AxiomNode
    struc_eq: AxiomNode
    struc_ne: AxiomNode

class ReflyNode(AxiomNode):
    Code: AxiomNode
    check: AxiomNode
    dbg: ReflyDbgNode
    debug: AxiomNode
    equiv: ReflyEquivNode
    error: AxiomNode
    gid: AxiomNode
    info: AxiomNode
    refine: AxiomNode
    reflect: AxiomNode
    reify: AxiomNode
    remove_dbg_repl: AxiomNode
    type: AxiomNode
    verbose: AxiomNode
    warn: AxiomNode

class RegexClsNode(AxiomNode):
    D: AxiomNode
    S: AxiomNode
    W: AxiomNode
    d: AxiomNode
    s: AxiomNode
    w: AxiomNode

class RegexQuantNode(AxiomNode):
    optional: AxiomNode
    plus: AxiomNode
    star: AxiomNode

class RegexNode(AxiomNode):
    any: AxiomNode
    cls: RegexClsNode
    conj: AxiomNode
    disj: AxiomNode
    empty: AxiomNode
    lit: AxiomNode
    lower_regex: AxiomNode
    neg_lookahead: AxiomNode
    not_: AxiomNode
    quant: RegexQuantNode
    range: AxiomNode

class TensorNode(AxiomNode):
    broadcast_in_dim: AxiomNode
    dot_2d_00: AxiomNode
    dot_2d_01: AxiomNode
    dot_2d_10: AxiomNode
    dot_2d_11: AxiomNode
    dot_general: AxiomNode
    map: AxiomNode
    map_reduce: AxiomNode
    reduce: AxiomNode
    reshape: AxiomNode
    slice: AxiomNode
    transpose: AxiomNode

class TupleNode(AxiomNode):
    append: AxiomNode
    cat: AxiomNode
    contains: AxiomNode
    prepend: AxiomNode
    typecat: AxiomNode
    zip: AxiomNode

class VecFoldNode(AxiomNode):
    l: AxiomNode
    r: AxiomNode

class VecScanNode(AxiomNode):
    exists: AxiomNode
    for_all: AxiomNode

class VecNode(AxiomNode):
    cat: AxiomNode
    diff: AxiomNode
    first: AxiomNode
    fold: VecFoldNode
    is_unique: AxiomNode
    last: AxiomNode
    len: AxiomNode
    scan: VecScanNode
    zip: AxiomNode

AXIOM_NAMESPACE_NAMES: tuple[str, ...]

def list_axioms() -> dict[str, tuple[str, ...]]: ...

Affine: AffineNode
Autodiff: AutodiffNode
Clos: ClosNode
Compile: CompileNode
Core: CoreNode
Demo: DemoNode
Direct: DirectNode
Gpu: GpuNode
Math: MathNode
Matrix: MatrixNode
Mem: MemNode
Opt: AxiomNode
Ord: OrdNode
Refly: ReflyNode
Regex: RegexNode
Tensor: TensorNode
Tuple: TupleNode
Vec: VecNode
