from __future__ import annotations

# This file is generated by scripts/generate_axiom_wrappers.py.
# Do not edit manually.

from typing import Sequence, TypeAlias

from ._mim_core import Def, World

AxiomStage: TypeAlias = Def | Sequence[Def]


class AxiomNode:
    @property
    def symbol(self) -> str | None: ...
    def __call__(self, world: World, *stages: AxiomStage, implicit: bool = False) -> Def: ...
    def __getattr__(self, name: str) -> AxiomNode: ...

class AffineForNode(AxiomNode):
    pass

class AffineLowerForPhaseNode(AxiomNode):
    pass

class AffineNode(AxiomNode):
    For: AxiomNode
    lower_for_phase: AxiomNode

class AutodiffADNode(AxiomNode):
    pass

class AutodiffTangentNode(AxiomNode):
    pass

class AutodiffAdNode(AxiomNode):
    pass

class AutodiffAddNode(AxiomNode):
    pass

class AutodiffEvalPassNode(AxiomNode):
    pass

class AutodiffSumNode(AxiomNode):
    pass

class AutodiffZeroNode(AxiomNode):
    pass

class AutodiffZeroReplNode(AxiomNode):
    pass

class AutodiffNode(AxiomNode):
    AD: AxiomNode
    Tangent: AxiomNode
    ad: AxiomNode
    add: AxiomNode
    eval_pass: AxiomNode
    sum: AxiomNode
    zero: AxiomNode
    zero_repl: AxiomNode

class ClosBufPtrNode(AxiomNode):
    pass

class ClosAllocJmpbufNode(AxiomNode):
    pass

class ClosAttrBottomNode(AxiomNode):
    pass

class ClosAttrEscNode(AxiomNode):
    pass

class ClosAttrFreeBBNode(AxiomNode):
    pass

class ClosAttrFstclassBBNode(AxiomNode):
    pass

class ClosAttrReturningNode(AxiomNode):
    pass

class ClosAttrNode(AxiomNode):
    bottom: AxiomNode
    esc: AxiomNode
    freeBB: AxiomNode
    fstclassBB: AxiomNode
    returning: AxiomNode

class ClosBranchClosPassNode(AxiomNode):
    pass

class ClosClos2sjljPassNode(AxiomNode):
    pass

class ClosClosConvPhaseNode(AxiomNode):
    pass

class ClosClosConvPrepPassNode(AxiomNode):
    pass

class ClosLongjmpNode(AxiomNode):
    pass

class ClosLowerTypedClosPhaseNode(AxiomNode):
    pass

class ClosLowerTypedClosPrepPassNode(AxiomNode):
    pass

class ClosSetjmpNode(AxiomNode):
    pass

class ClosNode(AxiomNode):
    BufPtr: AxiomNode
    alloc_jmpbuf: AxiomNode
    attr: ClosAttrNode
    branch_clos_pass: AxiomNode
    clos2sjlj_pass: AxiomNode
    clos_conv_phase: AxiomNode
    clos_conv_prep_pass: AxiomNode
    longjmp: AxiomNode
    lower_typed_clos_phase: AxiomNode
    lower_typed_clos_prep_pass: AxiomNode
    setjmp: AxiomNode

class CompilePassNode(AxiomNode):
    pass

class CompilePhaseNode(AxiomNode):
    pass

class CompileReplNode(AxiomNode):
    pass

class CompileBetaRedPassNode(AxiomNode):
    pass

class CompileBetaRedPhaseNode(AxiomNode):
    pass

class CompileBranchNormalizePhaseNode(AxiomNode):
    pass

class CompileCleanupPhaseNode(AxiomNode):
    pass

class CompileEtaExpPassNode(AxiomNode):
    pass

class CompileEtaExpPhaseNode(AxiomNode):
    pass

class CompileEtaRedPassNode(AxiomNode):
    pass

class CompileEtaRedPhaseNode(AxiomNode):
    pass

class CompileInternalCleanupPhaseNode(AxiomNode):
    pass

class CompileIsLoadedNode(AxiomNode):
    pass

class CompileLamSpecPassNode(AxiomNode):
    pass

class CompileNullPassNode(AxiomNode):
    pass

class CompileNullPhaseNode(AxiomNode):
    pass

class CompileNullReplNode(AxiomNode):
    pass

class CompilePass2phaseNode(AxiomNode):
    pass

class CompilePassesNode(AxiomNode):
    pass

class CompilePhasesNode(AxiomNode):
    pass

class CompilePrefixCleanupPhaseNode(AxiomNode):
    pass

class CompileRepl2phaseNode(AxiomNode):
    pass

class CompileReplsNode(AxiomNode):
    pass

class CompileRetWrapPhaseNode(AxiomNode):
    pass

class CompileScalarizePassNode(AxiomNode):
    pass

class CompileSymExprOptNode(AxiomNode):
    pass

class CompileTailRecElimPassNode(AxiomNode):
    pass

class CompileNode(AxiomNode):
    Pass: AxiomNode
    Phase: AxiomNode
    Repl: AxiomNode
    beta_red_pass: AxiomNode
    beta_red_phase: AxiomNode
    branch_normalize_phase: AxiomNode
    cleanup_phase: AxiomNode
    eta_exp_pass: AxiomNode
    eta_exp_phase: AxiomNode
    eta_red_pass: AxiomNode
    eta_red_phase: AxiomNode
    internal_cleanup_phase: AxiomNode
    is_loaded: AxiomNode
    lam_spec_pass: AxiomNode
    null_pass: AxiomNode
    null_phase: AxiomNode
    null_repl: AxiomNode
    pass2phase: AxiomNode
    passes: AxiomNode
    phases: AxiomNode
    prefix_cleanup_phase: AxiomNode
    repl2phase: AxiomNode
    repls: AxiomNode
    ret_wrap_phase: AxiomNode
    scalarize_pass: AxiomNode
    sym_expr_opt: AxiomNode
    tail_rec_elim_pass: AxiomNode

class CoreAbsNode(AxiomNode):
    pass

class CoreBit1FNode(AxiomNode):
    pass

class CoreBit1IdNode(AxiomNode):
    pass

class CoreBit1NegNode(AxiomNode):
    pass

class CoreBit1TNode(AxiomNode):
    pass

class CoreBit1Node(AxiomNode):
    f: AxiomNode
    id: AxiomNode
    neg: AxiomNode
    t: AxiomNode

class CoreBit2AndNode(AxiomNode):
    pass

class CoreBit2CiffNode(AxiomNode):
    pass

class CoreBit2FNode(AxiomNode):
    pass

class CoreBit2FstNode(AxiomNode):
    pass

class CoreBit2IffNode(AxiomNode):
    pass

class CoreBit2NandNode(AxiomNode):
    pass

class CoreBit2NciffNode(AxiomNode):
    pass

class CoreBit2NfstNode(AxiomNode):
    pass

class CoreBit2NiffNode(AxiomNode):
    pass

class CoreBit2NorNode(AxiomNode):
    pass

class CoreBit2NsndNode(AxiomNode):
    pass

class CoreBit2NxorNode(AxiomNode):
    pass

class CoreBit2OrNode(AxiomNode):
    pass

class CoreBit2SndNode(AxiomNode):
    pass

class CoreBit2TNode(AxiomNode):
    pass

class CoreBit2XorNode(AxiomNode):
    pass

class CoreBit2Node(AxiomNode):
    and_: AxiomNode
    ciff: AxiomNode
    f: AxiomNode
    fst: AxiomNode
    iff: AxiomNode
    nand: AxiomNode
    nciff: AxiomNode
    nfst: AxiomNode
    niff: AxiomNode
    nor: AxiomNode
    nsnd: AxiomNode
    nxor: AxiomNode
    or_: AxiomNode
    snd: AxiomNode
    t: AxiomNode
    xor_: AxiomNode

class CoreBitcastNode(AxiomNode):
    pass

class CoreConvSNode(AxiomNode):
    pass

class CoreConvUNode(AxiomNode):
    pass

class CoreConvNode(AxiomNode):
    s: AxiomNode
    u: AxiomNode

class CoreDivSdivNode(AxiomNode):
    pass

class CoreDivSremNode(AxiomNode):
    pass

class CoreDivUdivNode(AxiomNode):
    pass

class CoreDivUremNode(AxiomNode):
    pass

class CoreDivNode(AxiomNode):
    sdiv: AxiomNode
    srem: AxiomNode
    udiv: AxiomNode
    urem: AxiomNode

class CoreExtremaSMNode(AxiomNode):
    pass

class CoreExtremaSmNode(AxiomNode):
    pass

class CoreExtremaSmaxNode(AxiomNode):
    pass

class CoreExtremaSminNode(AxiomNode):
    pass

class CoreExtremaUmaxNode(AxiomNode):
    pass

class CoreExtremaUminNode(AxiomNode):
    pass

class CoreExtremaNode(AxiomNode):
    SM: AxiomNode
    Sm: AxiomNode
    sM: AxiomNode
    sm: AxiomNode
    smax: AxiomNode
    smin: AxiomNode
    umax: AxiomNode
    umin: AxiomNode

class CoreIcmpXYGLENode(AxiomNode):
    pass

class CoreIcmpXYGLeNode(AxiomNode):
    pass

class CoreIcmpXYGlENode(AxiomNode):
    pass

class CoreIcmpXYGleNode(AxiomNode):
    pass

class CoreIcmpXYgLENode(AxiomNode):
    pass

class CoreIcmpXYgLeNode(AxiomNode):
    pass

class CoreIcmpXYglENode(AxiomNode):
    pass

class CoreIcmpXYgleNode(AxiomNode):
    pass

class CoreIcmpXyGLENode(AxiomNode):
    pass

class CoreIcmpXyGLeNode(AxiomNode):
    pass

class CoreIcmpXyGlENode(AxiomNode):
    pass

class CoreIcmpXyGleNode(AxiomNode):
    pass

class CoreIcmpXygLENode(AxiomNode):
    pass

class CoreIcmpXygLeNode(AxiomNode):
    pass

class CoreIcmpXyglENode(AxiomNode):
    pass

class CoreIcmpXygleNode(AxiomNode):
    pass

class CoreIcmpENode(AxiomNode):
    pass

class CoreIcmpFNode(AxiomNode):
    pass

class CoreIcmpNeNode(AxiomNode):
    pass

class CoreIcmpSgNode(AxiomNode):
    pass

class CoreIcmpSgeNode(AxiomNode):
    pass

class CoreIcmpSlNode(AxiomNode):
    pass

class CoreIcmpSleNode(AxiomNode):
    pass

class CoreIcmpTNode(AxiomNode):
    pass

class CoreIcmpUgNode(AxiomNode):
    pass

class CoreIcmpUgeNode(AxiomNode):
    pass

class CoreIcmpUlNode(AxiomNode):
    pass

class CoreIcmpUleNode(AxiomNode):
    pass

class CoreIcmpNode(AxiomNode):
    XYGLE: AxiomNode
    XYGLe: AxiomNode
    XYGlE: AxiomNode
    XYGle: AxiomNode
    XYgLE: AxiomNode
    XYgLe: AxiomNode
    XYglE: AxiomNode
    XYgle: AxiomNode
    XyGLE: AxiomNode
    XyGLe: AxiomNode
    XyGlE: AxiomNode
    XyGle: AxiomNode
    XygLE: AxiomNode
    XygLe: AxiomNode
    XyglE: AxiomNode
    Xygle: AxiomNode
    e: AxiomNode
    f: AxiomNode
    ne: AxiomNode
    sg: AxiomNode
    sge: AxiomNode
    sl: AxiomNode
    sle: AxiomNode
    t: AxiomNode
    ug: AxiomNode
    uge: AxiomNode
    ul: AxiomNode
    ule: AxiomNode
    xYGLE: AxiomNode
    xYGLe: AxiomNode
    xYGlE: AxiomNode
    xYGle: AxiomNode
    xYgLE: AxiomNode
    xYgLe: AxiomNode
    xYglE: AxiomNode
    xYgle: AxiomNode
    xyGLE: AxiomNode
    xyGLe: AxiomNode
    xyGlE: AxiomNode
    xyGle: AxiomNode
    xygLE: AxiomNode
    xygLe: AxiomNode
    xyglE: AxiomNode
    xygle: AxiomNode

class CoreIdxNode(AxiomNode):
    pass

class CoreIdxUnsafeNode(AxiomNode):
    pass

class CoreMinusNode(AxiomNode):
    pass

class CoreModeUSNode(AxiomNode):
    pass

class CoreModeUsNode(AxiomNode):
    pass

class CoreModeNswNode(AxiomNode):
    pass

class CoreModeNuswNode(AxiomNode):
    pass

class CoreModeNuwNode(AxiomNode):
    pass

class CoreModeNode(AxiomNode):
    US: AxiomNode
    Us: AxiomNode
    nsw: AxiomNode
    nusw: AxiomNode
    nuw: AxiomNode
    uS: AxiomNode
    us: AxiomNode

class CoreNatAddNode(AxiomNode):
    pass

class CoreNatMulNode(AxiomNode):
    pass

class CoreNatSubNode(AxiomNode):
    pass

class CoreNatNode(AxiomNode):
    add: AxiomNode
    mul: AxiomNode
    sub: AxiomNode

class CoreNcmpGLENode(AxiomNode):
    pass

class CoreNcmpGLeNode(AxiomNode):
    pass

class CoreNcmpGlENode(AxiomNode):
    pass

class CoreNcmpGleNode(AxiomNode):
    pass

class CoreNcmpENode(AxiomNode):
    pass

class CoreNcmpFNode(AxiomNode):
    pass

class CoreNcmpGNode(AxiomNode):
    pass

class CoreNcmpGeNode(AxiomNode):
    pass

class CoreNcmpLNode(AxiomNode):
    pass

class CoreNcmpLeNode(AxiomNode):
    pass

class CoreNcmpNeNode(AxiomNode):
    pass

class CoreNcmpTNode(AxiomNode):
    pass

class CoreNcmpNode(AxiomNode):
    GLE: AxiomNode
    GLe: AxiomNode
    GlE: AxiomNode
    Gle: AxiomNode
    e: AxiomNode
    f: AxiomNode
    g: AxiomNode
    gLE: AxiomNode
    gLe: AxiomNode
    ge: AxiomNode
    glE: AxiomNode
    gle: AxiomNode
    l: AxiomNode
    le: AxiomNode
    ne: AxiomNode
    t: AxiomNode

class CorePeHltNode(AxiomNode):
    pass

class CorePeIsClosedNode(AxiomNode):
    pass

class CorePeRunNode(AxiomNode):
    pass

class CorePeNode(AxiomNode):
    hlt: AxiomNode
    is_closed: AxiomNode
    run: AxiomNode

class CoreSelectNode(AxiomNode):
    pass

class CoreShrANode(AxiomNode):
    pass

class CoreShrLNode(AxiomNode):
    pass

class CoreShrNode(AxiomNode):
    a: AxiomNode
    l: AxiomNode

class CoreTraitAlignNode(AxiomNode):
    pass

class CoreTraitSizeNode(AxiomNode):
    pass

class CoreTraitNode(AxiomNode):
    align: AxiomNode
    size: AxiomNode

class CoreWrapAddNode(AxiomNode):
    pass

class CoreWrapMulNode(AxiomNode):
    pass

class CoreWrapShlNode(AxiomNode):
    pass

class CoreWrapSubNode(AxiomNode):
    pass

class CoreWrapNode(AxiomNode):
    add: AxiomNode
    mul: AxiomNode
    shl: AxiomNode
    sub: AxiomNode

class CoreNode(AxiomNode):
    abs: AxiomNode
    bit1: CoreBit1Node
    bit2: CoreBit2Node
    bitcast: AxiomNode
    conv: CoreConvNode
    div: CoreDivNode
    extrema: CoreExtremaNode
    icmp: CoreIcmpNode
    idx: AxiomNode
    idx_unsafe: AxiomNode
    minus: AxiomNode
    mode: CoreModeNode
    nat: CoreNatNode
    ncmp: CoreNcmpNode
    pe: CorePeNode
    select: AxiomNode
    shr: CoreShrNode
    trait: CoreTraitNode
    wrap: CoreWrapNode

class DemoConstIdxNode(AxiomNode):
    pass

class DemoNode(AxiomNode):
    const_idx: AxiomNode

class DirectCps2dsNode(AxiomNode):
    pass

class DirectCps2dsDepNode(AxiomNode):
    pass

class DirectCps2dsPhaseNode(AxiomNode):
    pass

class DirectDs2cpsPhaseNode(AxiomNode):
    pass

class DirectNode(AxiomNode):
    cps2ds: AxiomNode
    cps2ds_dep: AxiomNode
    cps2ds_phase: AxiomNode
    ds2cps_phase: AxiomNode

class GpuConstMNode(AxiomNode):
    pass

class GpuConstPtrNode(AxiomNode):
    pass

class GpuDefaultStreamNode(AxiomNode):
    pass

class GpuGlobalMNode(AxiomNode):
    pass

class GpuGlobalPtrNode(AxiomNode):
    pass

class GpuLocalMNode(AxiomNode):
    pass

class GpuLocalPtrNode(AxiomNode):
    pass

class GpuSharedMNode(AxiomNode):
    pass

class GpuSharedPtrNode(AxiomNode):
    pass

class GpuStreamNode(AxiomNode):
    pass

class GpuAddrSpaceConstNode(AxiomNode):
    pass

class GpuAddrSpaceGlobalNode(AxiomNode):
    pass

class GpuAddrSpaceLocalNode(AxiomNode):
    pass

class GpuAddrSpaceSharedNode(AxiomNode):
    pass

class GpuAllocNode(AxiomNode):
    pass

class GpuAllocAsyncNode(AxiomNode):
    pass

class GpuAllocCopyNode(AxiomNode):
    pass

class GpuAllocCopyAsyncNode(AxiomNode):
    pass

class GpuCopyToDeviceNode(AxiomNode):
    pass

class GpuCopyToDeviceAsyncNode(AxiomNode):
    pass

class GpuCopyToHostNode(AxiomNode):
    pass

class GpuCopyToHostAsyncNode(AxiomNode):
    pass

class GpuFreeNode(AxiomNode):
    pass

class GpuFreeAsyncNode(AxiomNode):
    pass

class GpuLaunchNode(AxiomNode):
    pass

class GpuLaunchWithSmemNode(AxiomNode):
    pass

class GpuMalloc2gpuallocReplNode(AxiomNode):
    pass

class GpuStreamDeinitNode(AxiomNode):
    pass

class GpuStreamInitNode(AxiomNode):
    pass

class GpuStreamSyncNode(AxiomNode):
    pass

class GpuSyncWorkItemsNode(AxiomNode):
    pass

class GpuSyncedScopeNode(AxiomNode):
    pass

class GpuNode(AxiomNode):
    ConstM: AxiomNode
    ConstPtr: AxiomNode
    DefaultStream: AxiomNode
    GlobalM: AxiomNode
    GlobalPtr: AxiomNode
    LocalM: AxiomNode
    LocalPtr: AxiomNode
    SharedM: AxiomNode
    SharedPtr: AxiomNode
    Stream: AxiomNode
    addr_space_const: AxiomNode
    addr_space_global: AxiomNode
    addr_space_local: AxiomNode
    addr_space_shared: AxiomNode
    alloc: AxiomNode
    alloc_async: AxiomNode
    alloc_copy: AxiomNode
    alloc_copy_async: AxiomNode
    copy_to_device: AxiomNode
    copy_to_device_async: AxiomNode
    copy_to_host: AxiomNode
    copy_to_host_async: AxiomNode
    free: AxiomNode
    free_async: AxiomNode
    launch: AxiomNode
    launch_with_smem: AxiomNode
    malloc2gpualloc_repl: AxiomNode
    stream_deinit: AxiomNode
    stream_init: AxiomNode
    stream_sync: AxiomNode
    sync_work_items: AxiomNode
    synced_scope: AxiomNode

class MathAMDFP24Node(AxiomNode):
    pass

class MathBF16Node(AxiomNode):
    pass

class MathFNode(AxiomNode):
    pass

class MathF16Node(AxiomNode):
    pass

class MathF32Node(AxiomNode):
    pass

class MathF64Node(AxiomNode):
    pass

class MathNVTF32Node(AxiomNode):
    pass

class MathPXR24Node(AxiomNode):
    pass

class MathAbsNode(AxiomNode):
    pass

class MathAmdfp24Node(AxiomNode):
    pass

class MathArithAddNode(AxiomNode):
    pass

class MathArithDivNode(AxiomNode):
    pass

class MathArithMulNode(AxiomNode):
    pass

class MathArithRemNode(AxiomNode):
    pass

class MathArithSubNode(AxiomNode):
    pass

class MathArithNode(AxiomNode):
    add: AxiomNode
    div: AxiomNode
    mul: AxiomNode
    rem: AxiomNode
    sub: AxiomNode

class MathBf16Node(AxiomNode):
    pass

class MathCmpUGLENode(AxiomNode):
    pass

class MathCmpUGLeNode(AxiomNode):
    pass

class MathCmpUGlENode(AxiomNode):
    pass

class MathCmpUGleNode(AxiomNode):
    pass

class MathCmpUgLENode(AxiomNode):
    pass

class MathCmpUgLeNode(AxiomNode):
    pass

class MathCmpUglENode(AxiomNode):
    pass

class MathCmpUgleNode(AxiomNode):
    pass

class MathCmpENode(AxiomNode):
    pass

class MathCmpFNode(AxiomNode):
    pass

class MathCmpGNode(AxiomNode):
    pass

class MathCmpGeNode(AxiomNode):
    pass

class MathCmpLNode(AxiomNode):
    pass

class MathCmpLeNode(AxiomNode):
    pass

class MathCmpNeNode(AxiomNode):
    pass

class MathCmpONode(AxiomNode):
    pass

class MathCmpTNode(AxiomNode):
    pass

class MathCmpUNode(AxiomNode):
    pass

class MathCmpUeNode(AxiomNode):
    pass

class MathCmpUgNode(AxiomNode):
    pass

class MathCmpUgeNode(AxiomNode):
    pass

class MathCmpUlNode(AxiomNode):
    pass

class MathCmpUleNode(AxiomNode):
    pass

class MathCmpUneNode(AxiomNode):
    pass

class MathCmpNode(AxiomNode):
    UGLE: AxiomNode
    UGLe: AxiomNode
    UGlE: AxiomNode
    UGle: AxiomNode
    UgLE: AxiomNode
    UgLe: AxiomNode
    UglE: AxiomNode
    Ugle: AxiomNode
    e: AxiomNode
    f: AxiomNode
    g: AxiomNode
    ge: AxiomNode
    l: AxiomNode
    le: AxiomNode
    ne: AxiomNode
    o: AxiomNode
    t: AxiomNode
    u: AxiomNode
    uGLE: AxiomNode
    uGLe: AxiomNode
    uGlE: AxiomNode
    uGle: AxiomNode
    ue: AxiomNode
    ug: AxiomNode
    ugLE: AxiomNode
    ugLe: AxiomNode
    uge: AxiomNode
    uglE: AxiomNode
    ugle: AxiomNode
    ul: AxiomNode
    ule: AxiomNode
    une: AxiomNode

class MathConvF2fNode(AxiomNode):
    pass

class MathConvF2sNode(AxiomNode):
    pass

class MathConvF2uNode(AxiomNode):
    pass

class MathConvS2fNode(AxiomNode):
    pass

class MathConvU2fNode(AxiomNode):
    pass

class MathConvNode(AxiomNode):
    f2f: AxiomNode
    f2s: AxiomNode
    f2u: AxiomNode
    s2f: AxiomNode
    u2f: AxiomNode

class MathErFNode(AxiomNode):
    pass

class MathErFcNode(AxiomNode):
    pass

class MathErNode(AxiomNode):
    f: AxiomNode
    fc: AxiomNode

class MathExpLBBNode(AxiomNode):
    pass

class MathExpLBbNode(AxiomNode):
    pass

class MathExpLbBNode(AxiomNode):
    pass

class MathExpLbbNode(AxiomNode):
    pass

class MathExpBinNode(AxiomNode):
    pass

class MathExpDecNode(AxiomNode):
    pass

class MathExpExpNode(AxiomNode):
    pass

class MathExpExp10Node(AxiomNode):
    pass

class MathExpExp2Node(AxiomNode):
    pass

class MathExpLogNode(AxiomNode):
    pass

class MathExpLog10Node(AxiomNode):
    pass

class MathExpLog2Node(AxiomNode):
    pass

class MathExpNode(AxiomNode):
    LBB: AxiomNode
    LBb: AxiomNode
    LbB: AxiomNode
    Lbb: AxiomNode
    bin: AxiomNode
    dec: AxiomNode
    exp: AxiomNode
    exp10: AxiomNode
    exp2: AxiomNode
    lBB: AxiomNode
    lBb: AxiomNode
    lbB: AxiomNode
    lbb: AxiomNode
    log: AxiomNode
    log10: AxiomNode
    log2: AxiomNode

class MathExtremaIMNode(AxiomNode):
    pass

class MathExtremaImNode(AxiomNode):
    pass

class MathExtremaFmaxNode(AxiomNode):
    pass

class MathExtremaFminNode(AxiomNode):
    pass

class MathExtremaIeee754maxNode(AxiomNode):
    pass

class MathExtremaIeee754minNode(AxiomNode):
    pass

class MathExtremaNode(AxiomNode):
    IM: AxiomNode
    Im: AxiomNode
    fmax: AxiomNode
    fmin: AxiomNode
    iM: AxiomNode
    ieee754max: AxiomNode
    ieee754min: AxiomNode
    im: AxiomNode

class MathGammaLNode(AxiomNode):
    pass

class MathGammaTNode(AxiomNode):
    pass

class MathGammaNode(AxiomNode):
    l: AxiomNode
    t: AxiomNode

class MathMinusNode(AxiomNode):
    pass

class MathNvtf32Node(AxiomNode):
    pass

class MathPowNode(AxiomNode):
    pass

class MathPxr24Node(AxiomNode):
    pass

class MathRoundCNode(AxiomNode):
    pass

class MathRoundFNode(AxiomNode):
    pass

class MathRoundRNode(AxiomNode):
    pass

class MathRoundTNode(AxiomNode):
    pass

class MathRoundNode(AxiomNode):
    c: AxiomNode
    f: AxiomNode
    r: AxiomNode
    t: AxiomNode

class MathRrtNode(AxiomNode):
    pass

class MathRtCbNode(AxiomNode):
    pass

class MathRtSqNode(AxiomNode):
    pass

class MathRtNode(AxiomNode):
    cb: AxiomNode
    sq: AxiomNode

class MathSgnNode(AxiomNode):
    pass

class MathSlfNode(AxiomNode):
    pass

class MathTriAHFFNode(AxiomNode):
    pass

class MathTriAHFfNode(AxiomNode):
    pass

class MathTriAHfFNode(AxiomNode):
    pass

class MathTriAHffNode(AxiomNode):
    pass

class MathTriAhFFNode(AxiomNode):
    pass

class MathTriAhFfNode(AxiomNode):
    pass

class MathTriAhfFNode(AxiomNode):
    pass

class MathTriAhffNode(AxiomNode):
    pass

class MathTriANode(AxiomNode):
    pass

class MathTriAcosNode(AxiomNode):
    pass

class MathTriAcoshNode(AxiomNode):
    pass

class MathTriAsinNode(AxiomNode):
    pass

class MathTriAsinhNode(AxiomNode):
    pass

class MathTriAtanNode(AxiomNode):
    pass

class MathTriAtanhNode(AxiomNode):
    pass

class MathTriCosNode(AxiomNode):
    pass

class MathTriCoshNode(AxiomNode):
    pass

class MathTriHNode(AxiomNode):
    pass

class MathTriSinNode(AxiomNode):
    pass

class MathTriSinhNode(AxiomNode):
    pass

class MathTriTanNode(AxiomNode):
    pass

class MathTriTanhNode(AxiomNode):
    pass

class MathTriNode(AxiomNode):
    AHFF: AxiomNode
    AHFf: AxiomNode
    AHfF: AxiomNode
    AHff: AxiomNode
    AhFF: AxiomNode
    AhFf: AxiomNode
    AhfF: AxiomNode
    Ahff: AxiomNode
    a: AxiomNode
    aHFF: AxiomNode
    aHFf: AxiomNode
    aHfF: AxiomNode
    aHff: AxiomNode
    acos: AxiomNode
    acosh: AxiomNode
    ahFF: AxiomNode
    ahFf: AxiomNode
    ahfF: AxiomNode
    ahff: AxiomNode
    asin: AxiomNode
    asinh: AxiomNode
    atan: AxiomNode
    atanh: AxiomNode
    cos: AxiomNode
    cosh: AxiomNode
    h: AxiomNode
    sin: AxiomNode
    sinh: AxiomNode
    tan: AxiomNode
    tanh: AxiomNode

class MathNode(AxiomNode):
    AMDFP24: AxiomNode
    BF16: AxiomNode
    F: AxiomNode
    F16: AxiomNode
    F32: AxiomNode
    F64: AxiomNode
    NVTF32: AxiomNode
    PXR24: AxiomNode
    abs: AxiomNode
    amdfp24: AxiomNode
    arith: MathArithNode
    bf16: AxiomNode
    cmp: MathCmpNode
    conv: MathConvNode
    er: MathErNode
    exp: MathExpNode
    extrema: MathExtremaNode
    f16: AxiomNode
    f32: AxiomNode
    f64: AxiomNode
    gamma: MathGammaNode
    minus: AxiomNode
    nvtf32: AxiomNode
    pow: AxiomNode
    pxr24: AxiomNode
    round: MathRoundNode
    rrt: AxiomNode
    rt: MathRtNode
    sgn: AxiomNode
    slf: AxiomNode
    tri: MathTriNode

class MatrixMatNode(AxiomNode):
    pass

class MatrixConstMatNode(AxiomNode):
    pass

class MatrixInitNode(AxiomNode):
    pass

class MatrixInsertNode(AxiomNode):
    pass

class MatrixLowerMatrixHighLevelMapReduceNode(AxiomNode):
    pass

class MatrixLowerMatrixLowLevelNode(AxiomNode):
    pass

class MatrixLowerMatrixMediumLevelNode(AxiomNode):
    pass

class MatrixMapReduceNode(AxiomNode):
    pass

class MatrixProdNode(AxiomNode):
    pass

class MatrixReadNode(AxiomNode):
    pass

class MatrixShapeNode(AxiomNode):
    pass

class MatrixSumNode(AxiomNode):
    pass

class MatrixTransposeNode(AxiomNode):
    pass

class MatrixNode(AxiomNode):
    Mat: AxiomNode
    constMat: AxiomNode
    init: AxiomNode
    insert: AxiomNode
    lower_matrix_high_level_map_reduce: AxiomNode
    lower_matrix_low_level: AxiomNode
    lower_matrix_medium_level: AxiomNode
    map_reduce: AxiomNode
    prod: AxiomNode
    read: AxiomNode
    shape: AxiomNode
    sum: AxiomNode
    transpose: AxiomNode

class MemMNode(AxiomNode):
    pass

class MemPtrNode(AxiomNode):
    pass

class MemPtr0Node(AxiomNode):
    pass

class MemAddMemPhaseNode(AxiomNode):
    pass

class MemAllocNode(AxiomNode):
    pass

class MemAlloc2mallocReplNode(AxiomNode):
    pass

class MemCopyPropPassNode(AxiomNode):
    pass

class MemFreeNode(AxiomNode):
    pass

class MemLeaNode(AxiomNode):
    pass

class MemLoadNode(AxiomNode):
    pass

class MemMallocNode(AxiomNode):
    pass

class MemMslotNode(AxiomNode):
    pass

class MemRememNode(AxiomNode):
    pass

class MemRememReplNode(AxiomNode):
    pass

class MemReshapeArgNode(AxiomNode):
    pass

class MemReshapeFlatNode(AxiomNode):
    pass

class MemReshapeModeNode(AxiomNode):
    pass

class MemReshapePassNode(AxiomNode):
    pass

class MemSlotNode(AxiomNode):
    pass

class MemSsaPassNode(AxiomNode):
    pass

class MemStoreNode(AxiomNode):
    pass

class MemNode(AxiomNode):
    M: AxiomNode
    Ptr: AxiomNode
    Ptr0: AxiomNode
    add_mem_phase: AxiomNode
    alloc: AxiomNode
    alloc2malloc_repl: AxiomNode
    copy_prop_pass: AxiomNode
    free: AxiomNode
    lea: AxiomNode
    load: AxiomNode
    malloc: AxiomNode
    mslot: AxiomNode
    remem: AxiomNode
    remem_repl: AxiomNode
    reshape_arg: AxiomNode
    reshape_flat: AxiomNode
    reshape_mode: AxiomNode
    reshape_pass: AxiomNode
    slot: AxiomNode
    ssa_pass: AxiomNode
    store: AxiomNode

class OptNode(AxiomNode):
    pass

class OrdKeyNode(AxiomNode):
    pass

class OrdMapNode(AxiomNode):
    pass

class OrdSetNode(AxiomNode):
    pass

class OrdContainsMapNode(AxiomNode):
    pass

class OrdContainsSetNode(AxiomNode):
    pass

class OrdContainsNode(AxiomNode):
    map: AxiomNode
    set: AxiomNode

class OrdCreateMapNode(AxiomNode):
    pass

class OrdCreateSetNode(AxiomNode):
    pass

class OrdGetNode(AxiomNode):
    pass

class OrdInitMapNode(AxiomNode):
    pass

class OrdInitSetNode(AxiomNode):
    pass

class OrdInitNode(AxiomNode):
    map: AxiomNode
    set: AxiomNode

class OrdInsertMapNode(AxiomNode):
    pass

class OrdInsertSetNode(AxiomNode):
    pass

class OrdInsertNode(AxiomNode):
    map: AxiomNode
    set: AxiomNode

class OrdIsEmptyMapNode(AxiomNode):
    pass

class OrdIsEmptySetNode(AxiomNode):
    pass

class OrdSizeMapNode(AxiomNode):
    pass

class OrdSizeSetNode(AxiomNode):
    pass

class OrdSizeNode(AxiomNode):
    map: AxiomNode
    set: AxiomNode

class OrdNode(AxiomNode):
    Key: AxiomNode
    Map: AxiomNode
    Set: AxiomNode
    contains: OrdContainsNode
    create_map: AxiomNode
    create_set: AxiomNode
    get: AxiomNode
    init: OrdInitNode
    insert: OrdInsertNode
    is_empty_map: AxiomNode
    is_empty_set: AxiomNode
    size: OrdSizeNode

class ReflyCodeNode(AxiomNode):
    pass

class ReflyCheckNode(AxiomNode):
    pass

class ReflyDbgPermNode(AxiomNode):
    pass

class ReflyDbgTmpNode(AxiomNode):
    pass

class ReflyDbgNode(AxiomNode):
    perm: AxiomNode
    tmp: AxiomNode

class ReflyDebugNode(AxiomNode):
    pass

class ReflyEquivAENode(AxiomNode):
    pass

class ReflyEquivAeNode(AxiomNode):
    pass

class ReflyEquivAlphaEqNode(AxiomNode):
    pass

class ReflyEquivAlphaNeNode(AxiomNode):
    pass

class ReflyEquivStrucEqNode(AxiomNode):
    pass

class ReflyEquivStrucNeNode(AxiomNode):
    pass

class ReflyEquivNode(AxiomNode):
    AE: AxiomNode
    Ae: AxiomNode
    aE: AxiomNode
    ae: AxiomNode
    alpha_eq: AxiomNode
    alpha_ne: AxiomNode
    struc_eq: AxiomNode
    struc_ne: AxiomNode

class ReflyErrorNode(AxiomNode):
    pass

class ReflyGidNode(AxiomNode):
    pass

class ReflyInfoNode(AxiomNode):
    pass

class ReflyRefineNode(AxiomNode):
    pass

class ReflyReflectNode(AxiomNode):
    pass

class ReflyReifyNode(AxiomNode):
    pass

class ReflyRemoveDbgReplNode(AxiomNode):
    pass

class ReflyTypeNode(AxiomNode):
    pass

class ReflyVerboseNode(AxiomNode):
    pass

class ReflyWarnNode(AxiomNode):
    pass

class ReflyNode(AxiomNode):
    Code: AxiomNode
    check: AxiomNode
    dbg: ReflyDbgNode
    debug: AxiomNode
    equiv: ReflyEquivNode
    error: AxiomNode
    gid: AxiomNode
    info: AxiomNode
    refine: AxiomNode
    reflect: AxiomNode
    reify: AxiomNode
    remove_dbg_repl: AxiomNode
    type: AxiomNode
    verbose: AxiomNode
    warn: AxiomNode

class RegexAnyNode(AxiomNode):
    pass

class RegexClsDNode(AxiomNode):
    pass

class RegexClsSNode(AxiomNode):
    pass

class RegexClsWNode(AxiomNode):
    pass

class RegexClsNode(AxiomNode):
    D: AxiomNode
    S: AxiomNode
    W: AxiomNode
    d: AxiomNode
    s: AxiomNode
    w: AxiomNode

class RegexConjNode(AxiomNode):
    pass

class RegexDisjNode(AxiomNode):
    pass

class RegexEmptyNode(AxiomNode):
    pass

class RegexLitNode(AxiomNode):
    pass

class RegexLowerRegexNode(AxiomNode):
    pass

class RegexNegLookaheadNode(AxiomNode):
    pass

class RegexNotNode(AxiomNode):
    pass

class RegexQuantOptionalNode(AxiomNode):
    pass

class RegexQuantPlusNode(AxiomNode):
    pass

class RegexQuantStarNode(AxiomNode):
    pass

class RegexQuantNode(AxiomNode):
    optional: AxiomNode
    plus: AxiomNode
    star: AxiomNode

class RegexRangeNode(AxiomNode):
    pass

class RegexNode(AxiomNode):
    any: AxiomNode
    cls: RegexClsNode
    conj: AxiomNode
    disj: AxiomNode
    empty: AxiomNode
    lit: AxiomNode
    lower_regex: AxiomNode
    neg_lookahead: AxiomNode
    not_: AxiomNode
    quant: RegexQuantNode
    range: AxiomNode

class TensorBroadcastInDimNode(AxiomNode):
    pass

class TensorDot2d00Node(AxiomNode):
    pass

class TensorDot2d01Node(AxiomNode):
    pass

class TensorDot2d10Node(AxiomNode):
    pass

class TensorDot2d11Node(AxiomNode):
    pass

class TensorDotGeneralNode(AxiomNode):
    pass

class TensorMapNode(AxiomNode):
    pass

class TensorMapReduceNode(AxiomNode):
    pass

class TensorReduceNode(AxiomNode):
    pass

class TensorReshapeNode(AxiomNode):
    pass

class TensorSliceNode(AxiomNode):
    pass

class TensorTransposeNode(AxiomNode):
    pass

class TensorNode(AxiomNode):
    broadcast_in_dim: AxiomNode
    dot_2d_00: AxiomNode
    dot_2d_01: AxiomNode
    dot_2d_10: AxiomNode
    dot_2d_11: AxiomNode
    dot_general: AxiomNode
    map: AxiomNode
    map_reduce: AxiomNode
    reduce: AxiomNode
    reshape: AxiomNode
    slice: AxiomNode
    transpose: AxiomNode

class TupleAppendNode(AxiomNode):
    pass

class TupleCatNode(AxiomNode):
    pass

class TupleContainsNode(AxiomNode):
    pass

class TuplePrependNode(AxiomNode):
    pass

class TupleTypecatNode(AxiomNode):
    pass

class TupleZipNode(AxiomNode):
    pass

class TupleNode(AxiomNode):
    append: AxiomNode
    cat: AxiomNode
    contains: AxiomNode
    prepend: AxiomNode
    typecat: AxiomNode
    zip: AxiomNode

class VecCatNode(AxiomNode):
    pass

class VecDiffNode(AxiomNode):
    pass

class VecFirstNode(AxiomNode):
    pass

class VecFoldLNode(AxiomNode):
    pass

class VecFoldRNode(AxiomNode):
    pass

class VecFoldNode(AxiomNode):
    l: AxiomNode
    r: AxiomNode

class VecIsUniqueNode(AxiomNode):
    pass

class VecLastNode(AxiomNode):
    pass

class VecLenNode(AxiomNode):
    pass

class VecScanExistsNode(AxiomNode):
    pass

class VecScanForAllNode(AxiomNode):
    pass

class VecScanNode(AxiomNode):
    exists: AxiomNode
    for_all: AxiomNode

class VecZipNode(AxiomNode):
    pass

class VecNode(AxiomNode):
    cat: AxiomNode
    diff: AxiomNode
    first: AxiomNode
    fold: VecFoldNode
    is_unique: AxiomNode
    last: AxiomNode
    len: AxiomNode
    scan: VecScanNode
    zip: AxiomNode

AXIOM_NAMESPACE_NAMES: tuple[str, ...]


def list_axioms() -> dict[str, tuple[str, ...]]: ...


Affine: AffineNode
Autodiff: AutodiffNode
Clos: ClosNode
Compile: CompileNode
Core: CoreNode
Demo: DemoNode
Direct: DirectNode
Gpu: GpuNode
Math: MathNode
Matrix: MatrixNode
Mem: MemNode
Opt: OptNode
Ord: OrdNode
Refly: ReflyNode
Regex: RegexNode
Tensor: TensorNode
Tuple: TupleNode
Vec: VecNode
